prog_level_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("", include("quiz.urls")),
]
urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import (
    QuestionView,
    QuestionSearchView,
    QuizView,
    ResultsViewSet,
    ResultFormView,
    single_result_view,
)

router = routers.SimpleRouter()
router.register(r"api/result_list", ResultsViewSet)

app_name = "quiz"

urlpatterns = [
    path("", QuizView.as_view(), name="quiz-view"),
    path("<uuid:uuid>/", QuestionView.as_view(), name="question-view"),
    path("", include(router.urls)),
    path("find/", ResultFormView.as_view(), name="result-view"),
    path("training-result/<uuid:uuid>", single_result_view, name="training-view"),
    path("question-search", QuestionSearchView.as_view(), name="question-search"),
]

skillstrainer/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("", include("quiz.urls")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
import uuid
from django.db import models

from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from ckeditor_uploader.fields import RichTextUploadingField


SENIORITY_CHOICES = (
    (1, "junior"),
    (2, "regular"),
    (3, "senior"),
)

NUM_OF_QUESTIONS = (
    (6, 6),
    (9, 9),
    (12, 12),
)

QUESTION_TYPE_CHOICES = (
    ("multiple choice", "multiple choice"),
    ("open", "open"),
    ("true/false", "true/false"),
)

LANGUAGE_CHOICES = (
    ("English", "English"),
    ("Polish", "Polish"),
    ("German", "German"),
)

MODE_CHOICES = (
    ("recruitment", _("Recruitment")),
    ("training", _("Training")),
)


class Quiz(models.Model):
    objects = models.Manager()
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    category = models.ManyToManyField("Category", verbose_name=_("category"))
    technology = models.ManyToManyField("Technology", verbose_name=_("technology"))
    user_name = models.CharField(_("Participant Name"), max_length=120)
    email = models.CharField(_("Participant Email"), max_length=120, unique=True)
    number_of_questions = models.IntegerField(
        _("Number of questions"), choices=NUM_OF_QUESTIONS
    )
    created_at = models.DateTimeField(default=timezone.now)
    mode = models.CharField(_("Mode"), max_length=32, choices=MODE_CHOICES)

    class Meta:
        verbose_name_plural = "quizzes"

    def __str__(self):
        return f"{self.user_name} - {self.email}"

    def clean(self):
        try:
            validate_email(self.email)
        except ValidationError:
            raise ValidationError(_("Email address is incorrect."))
        if Quiz.objects.filter(email=self.email).exists():
            raise ValidationError(_("Email address is already taken."))


class Question(models.Model):
    objects = models.Manager()
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    text = RichTextUploadingField(null=True, blank=True, config_name="special")
    question_type = models.CharField(max_length=64, choices=QUESTION_TYPE_CHOICES)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    technology = models.ForeignKey("Technology", on_delete=models.CASCADE)
    seniority = models.ForeignKey("Seniority", on_delete=models.PROTECT)
    author = models.ForeignKey(
        "Author", on_delete=models.CASCADE, null=True, blank=True
    )
    time = models.IntegerField(default=30, help_text="duration in minutes")
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.text}"

    def get_answers(self):
        return self.answer_set.all()

    def is_author(self):
        return True if self.author else False


class Answer(models.Model):
    objects = models.Manager()
    text = RichTextUploadingField(null=True, blank=True, config_name="special")
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, is_correct: {self.is_correct}"


class Author(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=64)
    company = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name} - {self.company}"


class Category(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=128)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Technology(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=128)

    class Meta:
        verbose_name_plural = "technologies"

    def __str__(self):
        return self.name


class Score(models.Model):
    objects = models.Manager()
    quiz = models.ForeignKey("Quiz", on_delete=models.CASCADE)
    technology = models.ForeignKey("Technology", on_delete=models.PROTECT)
    seniority = models.ForeignKey(
        "Seniority", on_delete=models.PROTECT, null=True, blank=True
    )
    score_data = models.JSONField(null=True)

    def __str__(self):
        return f"{self.technology} - {self.quiz}"


class Seniority(models.Model):
    objects = models.Manager()
    level = models.IntegerField(choices=SENIORITY_CHOICES, verbose_name=_("Seniority"))

    class Meta:
        verbose_name_plural = "seniority"

    def __str__(self):
        return f"{self.level}"

templates/base.html
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="canonical" href="https://appseed.us/admin-dashboards/django-dashboard-argon">

    <title>quiz app| {% block title %}{% endblock title %}</title>

    <!-- Icons -->
  <link rel="stylesheet" href="/static/assets/vendor/nucleo/css/nucleo.css" type="text/css">
  <link rel="stylesheet" href="/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" type="text/css">
  <link rel="icon" type="image/x-icon" href="/static/images/favicon.ico">

  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link rel="stylesheet" href="/static/assets/css/argon.css?v=1.2.0" type="text/css">

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">

    <!-- highlight style for snippets in ckeditor -->
    <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css">
  {% endblock stylesheets %}

  </head>

  <body class="">


    <div class="main-content" id="panel">

      {% block content %}{% endblock content %}

    </div>
    {% include "includes/scripts.html" %}

    <!-- Specific JS goes HERE  -->
  {% block javascripts %}
    <script src="/static/js/copy_input.js"></script>
    <script>
      if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
      }
  </script>
  {% endblock javascripts %}

  </body>
</html>

templates/boolean_question.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block javascripts %}
    <script src="/static/js/question.js"></script>
    <!-- highlight.js files -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js" integrity="sha256-nxnOvB1EQa4fD/xpakJii5+GX+XZne2h8ejNW+yHiIg=" crossorigin="anonymous"></script>
    <script>hljs.highlightAll();</script>
{% endblock javascripts %}

{% block title %}
    Single question boolean
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-sm">
        <div class="col1">
            <div id="question" data-question={{ question.uuid }} data-quiz={{ quiz.pk }}>
                {{ question.text | safe }}
            </div>
            <div id="answer">
                {% if correct_answers != None %}
                    <h4><div>{% translate "Correct answers:" %}</div></h4>
                    {% for ans in correct_answers %}
                        {% if ans.text == "<p>T</p>" %}
                            <div class="alert alert-success">{% translate "True" %}</div>
                        {% else %}
                            <div class="alert alert-success">{% translate "False" %}</div>
                        {% endif %}
                    {% endfor %}
                    {% include 'continue_form.html' %}
                    <div class="not-visible" id="zero-timer">1</div>
                {% else %}
                    <form id="answer-form" action="" method="post">
                        {% csrf_token %}
                        <label>{% translate "True" %}
                            <input type="radio" name="ans" value="T">
                        </label>
                        <label>{% translate "False" %}
                            <input type="radio" name="ans" value="F">
                        </label>
                        <br>
                        <button class="btn btn-default" type="submit" id="question-submit">{% translate "Send" %}</button>
                        <div class="not-visible" id="zero-timer">0</div>
                    </form>
                {% endif %}
                {% if question.is_author %}
                    <p>Autor: {{ question.author }}</p>
                {% endif %}
            </div>
        </div>
      </div>
      <div class="col-sm">
        <span></span>
      </div>
      <div class="col-sm">
        <div id="timer">
            <div class="not-visible" id="time" data-value={{ time }}></div>
        </div>
        {% if quiz.mode == "training" %}
            <div id="train-data">
                <h4><div class="alert alert-info">{% translate "Technology" %}: {{ question.technology }}</div></h4>
                <h4><div class="alert alert-info">{% translate "Seniority" %}: {{ question.seniority.get_level_display }}</div></h4>
            </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/continue_form.html
{% load static %}
{% load i18n %}

{% if next_uuid != None %}
    <form id="continue-form" action="{% url 'quiz:question-view' uuid=next_uuid %}?q={{quiz.pk}}" method="post">
        {% csrf_token %}
        <button class="btn btn-default" type="submit" name="continue-submit">{% translate "Next" %}</button>
    </form>
{% else %}
    <form id="continue-form" action="{% url 'quiz:training-view' uuid=quiz.uuid %}" method="get">
        <button class="btn btn-default" type="submit">{% translate "Next" %}</button>
    </form>
{% endif %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block scripts %}
    <script src="/static/js/main.js"></script>
{% endblock scripts %}

{% block title %}
    Index
{% endblock title %}

{% block content %}
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<!--  -->
<br>
<div class="full-div">
    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                <form id="timezone-form" action="{% url 'quiz:quiz-view' %}" method="post">
                    {% csrf_token %}
                    <label for="timezone">{% translate "Time zone:" %}</label> <br>
                    <select name="timezone" class="form-control">
                        {% for city, tz in timezones.items %}
                        <option value="{{ tz }}"{% if tz == TIME_ZONE %}selected{% elif tz == "" %}selected{% endif %}>{{ city }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <button class="btn btn-default" type="submit" id="timezone-submit">{% translate "Set timezone" %}</button>
                </form>
            </div>
        </div>
    </div>

<hr>
<!--  -->
<h1>Skillstrainer quiz generator</h1>
<br>
<div class="row">
    <div class="col-sm-5">
        <div class="form-group">
            <form id="quiz-form" action="" method="post">
                {% csrf_token %}
                {{ quiz_form.as_p }}
                <button class="btn btn-default" type="submit">{% translate "Save" %}</button>
            </form>
            {% if quiz_form_err and not message and not first_question_uuid %}
                <br>
                {% for error in quiz_form_err.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
            {% endif %}
            <br>
            <div id="seniority-div">
                {% if request.POST and selected_technologies %}
                    {% include 'seniority.html' %}
                {% elif request.POST and message %}
                    <div class="alert alert-danger">
                        <strong>{{ message }}</strong>
                    </div>
                {% endif %}
            </div>

            {% if request.POST and first_question_uuid %}
                <div class="copy-link">
                    <input type="text" class="form-control copy-link-input" value="http://127.0.0.1:8000/{{ first_question_uuid }}?q={{ quiz_pk }}"
                        placeholder="quiz link" id="copy-input" readonly>
                    <span class="input-group-btn">
                        <br>
                        <button class="btn btn-default copy-link-button" type="button" id="copy-button" title={% translate "Copy" %}>{% translate "Copy" %}</button>
                    </span>
                </div>
            {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/question-search.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block javascripts %}
    <!-- highlight.js files -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js" integrity="sha256-nxnOvB1EQa4fD/xpakJii5+GX+XZne2h8ejNW+yHiIg=" crossorigin="anonymous"></script>
    <script>hljs.highlightAll();</script>
{% endblock javascripts %}


{% block title %}
    Question Search
{% endblock title %}


{% block content %}
<div class="container">
    <div class="row">
      <div class="col-sm-5">
        <h3>{% translate "Find a single question (enter id or uuid):" %}</h3>
        <div class="form-group">
          <form id="question-form" action="" method="post">
              {% csrf_token %}
              {{ question_form.as_p }}
              <button class="btn btn-default" type="submit" id="question-submit">{% translate "Find" %}</button>
          </form>
          <br>
        </div>
      </div>
      <div class="col">
        <div id="question" data-question={{ question.uuid }} data-quiz={{ quiz.pk }}>
          {{ question.text | safe }}
        </div>
        <div id="answer">
          {% if question and question.question_type == "multiple choice" %}
            <form id="answer-form" action="" method="post">
              {% csrf_token %}
              {% for answer in answers %}
              <label>
                  <input type="checkbox" name={{ answer.pk }} value={{ answer.pk }} class="left">{{ answer.text | safe}}
              </label>
              <br>
              {% endfor %}
            </form>
          {% elif question and question.question_type == "open" %}
            <form id="answer-form" action="" method="post">
              {% csrf_token %}
              {% translate "Your answer:" %}
              <label>
                <input type="text" name="ans">
              </label>
              <br>
            </form>
          {% elif question and question.question_type == "true/false" %}
            <form id="answer-form" action="" method="post">
              {% csrf_token %}
              <label>{% translate "True" %}
                <input type="radio" name="ans" value="T">
              </label>
              <label>{% translate "False" %}
                <input type="radio" name="ans" value="F">
              </label>
              <br>
            </form>
          {% endif %}
        </div>
      </div>
    </div>
</div>
{% endblock content %}

templates/results.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js" integrity="sha256-GcknncGKzlKm69d+sp+k3A2NyQE+jnu43aBl6rrDN2I=" crossorigin="anonymous"></script>
    <script src="/static/js/results.js"></script>
{% endblock javascripts %}

{% block title %}
    Results
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
        <form id="result-form" action="{% url 'quiz:result-view' %}" method="post">
            {% csrf_token %}
            {{ quiz_form.as_p }}
            <button class="btn btn-default" type="submit" id="result-submit">{% translate "Find" %}</button>
        </form>
        </div>
        <br>
      </div>
    </div>
    {% if quiz %}
        <div class="not-visible" id="training">Y</div>
        <div id="results" data-results="{{ json_obj }}"></div>
        <div class="row-wrapper"></div>
    {% endif %}
  </div>
{% endblock content %}

templates/seniority.html
{% load static %}
{% load i18n %}

<h3>{% translate "Please set initial seniority for each technology in quiz:" %}</h3>
<form id="tech-form" action="" method="post">
    {% csrf_token %}
    {% for technology in selected_technologies %}
        <div class="font-weight-bold">{{ technology }}: </div>
        {% for seniority in seniority_levels %}
        <div class="form-check form-check-inline">
            <label class="form-check-label"> {{ seniority.1 }}
            <input type="radio" class="form-check-input" name={{ technology }} value={{ seniority.0 }}>
            </label>
        </div>
        {% endfor %}
        <hr>
    {% endfor %}
    <button class="btn btn-default" type="submit" name="tech-submit" value="">{% translate "Generate Quiz Link" %}</button>
</form>

templates/single_question.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block javascripts %}
    <script src="/static/js/question.js"></script>

    <!-- highlight.js files -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js" integrity="sha256-nxnOvB1EQa4fD/xpakJii5+GX+XZne2h8ejNW+yHiIg=" crossorigin="anonymous"></script>
    <script>hljs.highlightAll();</script>
{% endblock javascripts %}

{% block title %}
    Single question
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-sm">
        <div class="col1">
            <div id="question" data-question={{ question.uuid }} data-quiz={{ quiz.pk }}>
                {{ question.text | safe }}
            </div>
            <div id="answer">
                {% if correct_answers != None %}
                    <h4><div>{% translate "Correct answers:" %}</div></h4>
                    {% if correct_answers|length == 0 %}
                        <div class="alert alert-success">{% translate "None of previously showed answers was correct." %}</div>
                    {% else %}
                        {% for ans in correct_answers %}
                            <div class="alert alert-success">{{ ans.text | safe}}</div>
                        {% endfor %}
                    {% endif %}
                    {% include 'continue_form.html' %}
                    <div class="not-visible" id="zero-timer">1</div>
                {% else %}
                    <form id="answer-form" action="" method="post">
                        {% csrf_token %}
                        {% for answer in answers %}
                        <label>
                            <input type="checkbox" name={{ answer.pk }} value={{ answer.pk }} class="left">{{ answer.text | safe}}
                        </label>
                        <br>
                        {% endfor %}
                        <button class="btn btn-default" type="submit" id="question-submit">{% translate "Send" %}</button>
                        <div class="not-visible" id="zero-timer">0</div>
                    </form>
                {% endif %}
                {% if question.is_author %}
                    <p>Autor: {{ question.author }}</p>
                {% endif %}
            </div>
        </div>
      </div>
      <div class="col-sm">
        <span></span>
      </div>
      <div class="col-sm">
        <div id="timer">
            <div class="not-visible" id="time" data-value={{ time }}></div>
        </div>
        {% if quiz.mode == "training" %}
            <div id="train-data">
                <h4><div class="alert alert-info">{% translate "Technology" %}: {{ question.technology }}</div></h4>
                <h4><div class="alert alert-info">{% translate "Seniority" %}: {{ question.seniority.get_level_display }}</div></h4>
            </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/single_question_open.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block javascripts %}
    <script src="/static/js/question.js"></script>
    <!-- highlight.js files -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js" integrity="sha256-nxnOvB1EQa4fD/xpakJii5+GX+XZne2h8ejNW+yHiIg=" crossorigin="anonymous"></script>
    <script>hljs.highlightAll();</script>
{% endblock javascripts %}

{% block title %}
    Single question
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-sm">
        <div class="col1">
            <div id="question" data-question={{ question.uuid }} data-quiz={{ quiz.pk }}>
                {{ question.text | safe }}
            </div>
            <div id="answer">
                {% if correct_answers != None %}
                    <h4><div>{% translate "Correct answers:" %}</div></h4>
                    {% for ans in correct_answers %}
                        <div class="alert alert-success">{{ ans.text | safe}}</div>
                    {% endfor %}
                    {% include 'continue_form.html' %}
                    <div class="not-visible" id="zero-timer">1</div>
                {% else %}
                    <form id="answer-form" action="" method="post">
                        {% csrf_token %}
                        {% translate "Your answer:" %}
                        <label>
                            <input type="text" name="ans">
                        </label>
                        <br>
                        <button class="btn btn-default" type="submit" id="question-submit">{% translate "Send" %}</button>
                        <div class="not-visible" id="zero-timer">0</div>
                    </form>
                {% endif %}
                {% if question.is_author %}
                    <p>Autor: {{ question.author }}</p>
                {% endif %}
            </div>
        </div>
      </div>
      <div class="col-sm">
        <span></span>
      </div>
      <div class="col-sm">
            <div class="col" id="timer">
                <div class="not-visible" id="time" data-value={{ time }}></div>
            </div>
            {% if quiz.mode == "training" %}
                <div id="train-data">
                    <h4><div class="alert alert-info">{% translate "Technology" %}: {{ question.technology }}</div></h4>
                    <h4><div class="alert alert-info">{% translate "Seniority" %}: {{ question.seniority.get_level_display }}</div></h4>
                </div>
            {% endif %}
    </div>
  </div>
{% endblock content %}

templates/single_result.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js" integrity="sha256-GcknncGKzlKm69d+sp+k3A2NyQE+jnu43aBl6rrDN2I=" crossorigin="anonymous"></script>
    <script src="/static/js/results.js"></script>
{% endblock javascripts %}

{% block title %}
  Single Result
{% endblock title %}


{% block content %}
<div class="container">
    {% if quiz %}
    <h3>
      Congratulations {{quiz.user_name}}!
      <br>
      You finished your quiz.
      <br>
      {% if training %}
      <small class="text-muted">Here are some results:</small>
      <div class="not-visible" id="training">Y</div>
      {% else %}
        <br>
        We will contact you and inform about the result. Thank you for participating!
      {% endif %}
    </h3>
    <br>
        <div id="results" data-results="{{ json_obj }}"></div>
        <div class="row-wrapper"></div>
    {% endif %}
  </div>
{% endblock content %}